language: android
jdk: oraclejdk8
dist: trusty
sudo: required
jdk:
  - oraclejdk8
env:
 global:
  # These parameters should match the parameters for build tools and sdk versions in the gradle file
   - ANDROID_BUILD_TOOLS=28.0.3 # should match gradle
   - ADB_INSTALL_TIMEOUT=5 # minutes
   - ANDROID_API=28 # api is same as gradle file
   - CC=clang
   - CXX=clang++
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - extra-google-google_play_services
    - addon-google_apis-google-19 # google play services
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
  - sudo chmod +x gradlew
  - wget https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
  - unzip android-ndk-r17c-linux-x86_64.zip -d $HOME
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r17c
  - export PATH=$PATH:$ANDROID_NDK_HOME
install:
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - echo y | sdkmanager 'lldb;3.0'
before_script:
  - touch local.properties
  - ./gradlew clean
